// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: register.proto

package com.ntuc.income.up.model;

public final class RegisterOuterClass {
  private RegisterOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RegisterOrBuilder extends
      // @@protoc_insertion_point(interface_extends:model.Register)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string identityTypeList = 1;</code>
     */
    java.lang.String getIdentityTypeList();
    /**
     * <code>string identityTypeList = 1;</code>
     */
    com.google.protobuf.ByteString
        getIdentityTypeListBytes();

    /**
     * <code>string identityType = 2;</code>
     */
    java.lang.String getIdentityType();
    /**
     * <code>string identityType = 2;</code>
     */
    com.google.protobuf.ByteString
        getIdentityTypeBytes();

    /**
     * <code>string dateOfBirth = 3;</code>
     */
    java.lang.String getDateOfBirth();
    /**
     * <code>string dateOfBirth = 3;</code>
     */
    com.google.protobuf.ByteString
        getDateOfBirthBytes();

    /**
     * <code>string emailAddress = 4;</code>
     */
    java.lang.String getEmailAddress();
    /**
     * <code>string emailAddress = 4;</code>
     */
    com.google.protobuf.ByteString
        getEmailAddressBytes();

    /**
     * <code>string changeEmailAddress = 5;</code>
     */
    java.lang.String getChangeEmailAddress();
    /**
     * <code>string changeEmailAddress = 5;</code>
     */
    com.google.protobuf.ByteString
        getChangeEmailAddressBytes();

    /**
     * <code>string password = 6;</code>
     */
    java.lang.String getPassword();
    /**
     * <code>string password = 6;</code>
     */
    com.google.protobuf.ByteString
        getPasswordBytes();

    /**
     * <code>string confirmPassword = 7;</code>
     */
    java.lang.String getConfirmPassword();
    /**
     * <code>string confirmPassword = 7;</code>
     */
    com.google.protobuf.ByteString
        getConfirmPasswordBytes();
  }
  /**
   * Protobuf type {@code model.Register}
   */
  public  static final class Register extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:model.Register)
      RegisterOrBuilder {
    // Use Register.newBuilder() to construct.
    private Register(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Register() {
      identityTypeList_ = "";
      identityType_ = "";
      dateOfBirth_ = "";
      emailAddress_ = "";
      changeEmailAddress_ = "";
      password_ = "";
      confirmPassword_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Register(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              identityTypeList_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              identityType_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              dateOfBirth_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              emailAddress_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              changeEmailAddress_ = s;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              password_ = s;
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              confirmPassword_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ntuc.income.up.model.RegisterOuterClass.internal_static_model_Register_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ntuc.income.up.model.RegisterOuterClass.internal_static_model_Register_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ntuc.income.up.model.RegisterOuterClass.Register.class, com.ntuc.income.up.model.RegisterOuterClass.Register.Builder.class);
    }

    public static final int IDENTITYTYPELIST_FIELD_NUMBER = 1;
    private volatile java.lang.Object identityTypeList_;
    /**
     * <code>string identityTypeList = 1;</code>
     */
    public java.lang.String getIdentityTypeList() {
      java.lang.Object ref = identityTypeList_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        identityTypeList_ = s;
        return s;
      }
    }
    /**
     * <code>string identityTypeList = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdentityTypeListBytes() {
      java.lang.Object ref = identityTypeList_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        identityTypeList_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int IDENTITYTYPE_FIELD_NUMBER = 2;
    private volatile java.lang.Object identityType_;
    /**
     * <code>string identityType = 2;</code>
     */
    public java.lang.String getIdentityType() {
      java.lang.Object ref = identityType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        identityType_ = s;
        return s;
      }
    }
    /**
     * <code>string identityType = 2;</code>
     */
    public com.google.protobuf.ByteString
        getIdentityTypeBytes() {
      java.lang.Object ref = identityType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        identityType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DATEOFBIRTH_FIELD_NUMBER = 3;
    private volatile java.lang.Object dateOfBirth_;
    /**
     * <code>string dateOfBirth = 3;</code>
     */
    public java.lang.String getDateOfBirth() {
      java.lang.Object ref = dateOfBirth_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        dateOfBirth_ = s;
        return s;
      }
    }
    /**
     * <code>string dateOfBirth = 3;</code>
     */
    public com.google.protobuf.ByteString
        getDateOfBirthBytes() {
      java.lang.Object ref = dateOfBirth_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dateOfBirth_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EMAILADDRESS_FIELD_NUMBER = 4;
    private volatile java.lang.Object emailAddress_;
    /**
     * <code>string emailAddress = 4;</code>
     */
    public java.lang.String getEmailAddress() {
      java.lang.Object ref = emailAddress_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        emailAddress_ = s;
        return s;
      }
    }
    /**
     * <code>string emailAddress = 4;</code>
     */
    public com.google.protobuf.ByteString
        getEmailAddressBytes() {
      java.lang.Object ref = emailAddress_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        emailAddress_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CHANGEEMAILADDRESS_FIELD_NUMBER = 5;
    private volatile java.lang.Object changeEmailAddress_;
    /**
     * <code>string changeEmailAddress = 5;</code>
     */
    public java.lang.String getChangeEmailAddress() {
      java.lang.Object ref = changeEmailAddress_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        changeEmailAddress_ = s;
        return s;
      }
    }
    /**
     * <code>string changeEmailAddress = 5;</code>
     */
    public com.google.protobuf.ByteString
        getChangeEmailAddressBytes() {
      java.lang.Object ref = changeEmailAddress_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        changeEmailAddress_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PASSWORD_FIELD_NUMBER = 6;
    private volatile java.lang.Object password_;
    /**
     * <code>string password = 6;</code>
     */
    public java.lang.String getPassword() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        password_ = s;
        return s;
      }
    }
    /**
     * <code>string password = 6;</code>
     */
    public com.google.protobuf.ByteString
        getPasswordBytes() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        password_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CONFIRMPASSWORD_FIELD_NUMBER = 7;
    private volatile java.lang.Object confirmPassword_;
    /**
     * <code>string confirmPassword = 7;</code>
     */
    public java.lang.String getConfirmPassword() {
      java.lang.Object ref = confirmPassword_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        confirmPassword_ = s;
        return s;
      }
    }
    /**
     * <code>string confirmPassword = 7;</code>
     */
    public com.google.protobuf.ByteString
        getConfirmPasswordBytes() {
      java.lang.Object ref = confirmPassword_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        confirmPassword_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getIdentityTypeListBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, identityTypeList_);
      }
      if (!getIdentityTypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, identityType_);
      }
      if (!getDateOfBirthBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, dateOfBirth_);
      }
      if (!getEmailAddressBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, emailAddress_);
      }
      if (!getChangeEmailAddressBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, changeEmailAddress_);
      }
      if (!getPasswordBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, password_);
      }
      if (!getConfirmPasswordBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, confirmPassword_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getIdentityTypeListBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, identityTypeList_);
      }
      if (!getIdentityTypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, identityType_);
      }
      if (!getDateOfBirthBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, dateOfBirth_);
      }
      if (!getEmailAddressBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, emailAddress_);
      }
      if (!getChangeEmailAddressBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, changeEmailAddress_);
      }
      if (!getPasswordBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, password_);
      }
      if (!getConfirmPasswordBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, confirmPassword_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.ntuc.income.up.model.RegisterOuterClass.Register)) {
        return super.equals(obj);
      }
      com.ntuc.income.up.model.RegisterOuterClass.Register other = (com.ntuc.income.up.model.RegisterOuterClass.Register) obj;

      boolean result = true;
      result = result && getIdentityTypeList()
          .equals(other.getIdentityTypeList());
      result = result && getIdentityType()
          .equals(other.getIdentityType());
      result = result && getDateOfBirth()
          .equals(other.getDateOfBirth());
      result = result && getEmailAddress()
          .equals(other.getEmailAddress());
      result = result && getChangeEmailAddress()
          .equals(other.getChangeEmailAddress());
      result = result && getPassword()
          .equals(other.getPassword());
      result = result && getConfirmPassword()
          .equals(other.getConfirmPassword());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + IDENTITYTYPELIST_FIELD_NUMBER;
      hash = (53 * hash) + getIdentityTypeList().hashCode();
      hash = (37 * hash) + IDENTITYTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getIdentityType().hashCode();
      hash = (37 * hash) + DATEOFBIRTH_FIELD_NUMBER;
      hash = (53 * hash) + getDateOfBirth().hashCode();
      hash = (37 * hash) + EMAILADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getEmailAddress().hashCode();
      hash = (37 * hash) + CHANGEEMAILADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getChangeEmailAddress().hashCode();
      hash = (37 * hash) + PASSWORD_FIELD_NUMBER;
      hash = (53 * hash) + getPassword().hashCode();
      hash = (37 * hash) + CONFIRMPASSWORD_FIELD_NUMBER;
      hash = (53 * hash) + getConfirmPassword().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.ntuc.income.up.model.RegisterOuterClass.Register parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ntuc.income.up.model.RegisterOuterClass.Register parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ntuc.income.up.model.RegisterOuterClass.Register parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ntuc.income.up.model.RegisterOuterClass.Register parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ntuc.income.up.model.RegisterOuterClass.Register parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ntuc.income.up.model.RegisterOuterClass.Register parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ntuc.income.up.model.RegisterOuterClass.Register parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ntuc.income.up.model.RegisterOuterClass.Register parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ntuc.income.up.model.RegisterOuterClass.Register parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.ntuc.income.up.model.RegisterOuterClass.Register parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ntuc.income.up.model.RegisterOuterClass.Register parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ntuc.income.up.model.RegisterOuterClass.Register parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.ntuc.income.up.model.RegisterOuterClass.Register prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code model.Register}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:model.Register)
        com.ntuc.income.up.model.RegisterOuterClass.RegisterOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ntuc.income.up.model.RegisterOuterClass.internal_static_model_Register_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ntuc.income.up.model.RegisterOuterClass.internal_static_model_Register_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ntuc.income.up.model.RegisterOuterClass.Register.class, com.ntuc.income.up.model.RegisterOuterClass.Register.Builder.class);
      }

      // Construct using com.ntuc.income.up.model.RegisterOuterClass.Register.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        identityTypeList_ = "";

        identityType_ = "";

        dateOfBirth_ = "";

        emailAddress_ = "";

        changeEmailAddress_ = "";

        password_ = "";

        confirmPassword_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ntuc.income.up.model.RegisterOuterClass.internal_static_model_Register_descriptor;
      }

      public com.ntuc.income.up.model.RegisterOuterClass.Register getDefaultInstanceForType() {
        return com.ntuc.income.up.model.RegisterOuterClass.Register.getDefaultInstance();
      }

      public com.ntuc.income.up.model.RegisterOuterClass.Register build() {
        com.ntuc.income.up.model.RegisterOuterClass.Register result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.ntuc.income.up.model.RegisterOuterClass.Register buildPartial() {
        com.ntuc.income.up.model.RegisterOuterClass.Register result = new com.ntuc.income.up.model.RegisterOuterClass.Register(this);
        result.identityTypeList_ = identityTypeList_;
        result.identityType_ = identityType_;
        result.dateOfBirth_ = dateOfBirth_;
        result.emailAddress_ = emailAddress_;
        result.changeEmailAddress_ = changeEmailAddress_;
        result.password_ = password_;
        result.confirmPassword_ = confirmPassword_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ntuc.income.up.model.RegisterOuterClass.Register) {
          return mergeFrom((com.ntuc.income.up.model.RegisterOuterClass.Register)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ntuc.income.up.model.RegisterOuterClass.Register other) {
        if (other == com.ntuc.income.up.model.RegisterOuterClass.Register.getDefaultInstance()) return this;
        if (!other.getIdentityTypeList().isEmpty()) {
          identityTypeList_ = other.identityTypeList_;
          onChanged();
        }
        if (!other.getIdentityType().isEmpty()) {
          identityType_ = other.identityType_;
          onChanged();
        }
        if (!other.getDateOfBirth().isEmpty()) {
          dateOfBirth_ = other.dateOfBirth_;
          onChanged();
        }
        if (!other.getEmailAddress().isEmpty()) {
          emailAddress_ = other.emailAddress_;
          onChanged();
        }
        if (!other.getChangeEmailAddress().isEmpty()) {
          changeEmailAddress_ = other.changeEmailAddress_;
          onChanged();
        }
        if (!other.getPassword().isEmpty()) {
          password_ = other.password_;
          onChanged();
        }
        if (!other.getConfirmPassword().isEmpty()) {
          confirmPassword_ = other.confirmPassword_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ntuc.income.up.model.RegisterOuterClass.Register parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ntuc.income.up.model.RegisterOuterClass.Register) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object identityTypeList_ = "";
      /**
       * <code>string identityTypeList = 1;</code>
       */
      public java.lang.String getIdentityTypeList() {
        java.lang.Object ref = identityTypeList_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          identityTypeList_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string identityTypeList = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIdentityTypeListBytes() {
        java.lang.Object ref = identityTypeList_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          identityTypeList_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string identityTypeList = 1;</code>
       */
      public Builder setIdentityTypeList(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        identityTypeList_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string identityTypeList = 1;</code>
       */
      public Builder clearIdentityTypeList() {
        
        identityTypeList_ = getDefaultInstance().getIdentityTypeList();
        onChanged();
        return this;
      }
      /**
       * <code>string identityTypeList = 1;</code>
       */
      public Builder setIdentityTypeListBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        identityTypeList_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object identityType_ = "";
      /**
       * <code>string identityType = 2;</code>
       */
      public java.lang.String getIdentityType() {
        java.lang.Object ref = identityType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          identityType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string identityType = 2;</code>
       */
      public com.google.protobuf.ByteString
          getIdentityTypeBytes() {
        java.lang.Object ref = identityType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          identityType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string identityType = 2;</code>
       */
      public Builder setIdentityType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        identityType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string identityType = 2;</code>
       */
      public Builder clearIdentityType() {
        
        identityType_ = getDefaultInstance().getIdentityType();
        onChanged();
        return this;
      }
      /**
       * <code>string identityType = 2;</code>
       */
      public Builder setIdentityTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        identityType_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object dateOfBirth_ = "";
      /**
       * <code>string dateOfBirth = 3;</code>
       */
      public java.lang.String getDateOfBirth() {
        java.lang.Object ref = dateOfBirth_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          dateOfBirth_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string dateOfBirth = 3;</code>
       */
      public com.google.protobuf.ByteString
          getDateOfBirthBytes() {
        java.lang.Object ref = dateOfBirth_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          dateOfBirth_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string dateOfBirth = 3;</code>
       */
      public Builder setDateOfBirth(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        dateOfBirth_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string dateOfBirth = 3;</code>
       */
      public Builder clearDateOfBirth() {
        
        dateOfBirth_ = getDefaultInstance().getDateOfBirth();
        onChanged();
        return this;
      }
      /**
       * <code>string dateOfBirth = 3;</code>
       */
      public Builder setDateOfBirthBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        dateOfBirth_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object emailAddress_ = "";
      /**
       * <code>string emailAddress = 4;</code>
       */
      public java.lang.String getEmailAddress() {
        java.lang.Object ref = emailAddress_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          emailAddress_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string emailAddress = 4;</code>
       */
      public com.google.protobuf.ByteString
          getEmailAddressBytes() {
        java.lang.Object ref = emailAddress_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          emailAddress_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string emailAddress = 4;</code>
       */
      public Builder setEmailAddress(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        emailAddress_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string emailAddress = 4;</code>
       */
      public Builder clearEmailAddress() {
        
        emailAddress_ = getDefaultInstance().getEmailAddress();
        onChanged();
        return this;
      }
      /**
       * <code>string emailAddress = 4;</code>
       */
      public Builder setEmailAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        emailAddress_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object changeEmailAddress_ = "";
      /**
       * <code>string changeEmailAddress = 5;</code>
       */
      public java.lang.String getChangeEmailAddress() {
        java.lang.Object ref = changeEmailAddress_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          changeEmailAddress_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string changeEmailAddress = 5;</code>
       */
      public com.google.protobuf.ByteString
          getChangeEmailAddressBytes() {
        java.lang.Object ref = changeEmailAddress_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          changeEmailAddress_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string changeEmailAddress = 5;</code>
       */
      public Builder setChangeEmailAddress(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        changeEmailAddress_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string changeEmailAddress = 5;</code>
       */
      public Builder clearChangeEmailAddress() {
        
        changeEmailAddress_ = getDefaultInstance().getChangeEmailAddress();
        onChanged();
        return this;
      }
      /**
       * <code>string changeEmailAddress = 5;</code>
       */
      public Builder setChangeEmailAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        changeEmailAddress_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object password_ = "";
      /**
       * <code>string password = 6;</code>
       */
      public java.lang.String getPassword() {
        java.lang.Object ref = password_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          password_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string password = 6;</code>
       */
      public com.google.protobuf.ByteString
          getPasswordBytes() {
        java.lang.Object ref = password_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          password_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string password = 6;</code>
       */
      public Builder setPassword(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        password_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string password = 6;</code>
       */
      public Builder clearPassword() {
        
        password_ = getDefaultInstance().getPassword();
        onChanged();
        return this;
      }
      /**
       * <code>string password = 6;</code>
       */
      public Builder setPasswordBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        password_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object confirmPassword_ = "";
      /**
       * <code>string confirmPassword = 7;</code>
       */
      public java.lang.String getConfirmPassword() {
        java.lang.Object ref = confirmPassword_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          confirmPassword_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string confirmPassword = 7;</code>
       */
      public com.google.protobuf.ByteString
          getConfirmPasswordBytes() {
        java.lang.Object ref = confirmPassword_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          confirmPassword_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string confirmPassword = 7;</code>
       */
      public Builder setConfirmPassword(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        confirmPassword_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string confirmPassword = 7;</code>
       */
      public Builder clearConfirmPassword() {
        
        confirmPassword_ = getDefaultInstance().getConfirmPassword();
        onChanged();
        return this;
      }
      /**
       * <code>string confirmPassword = 7;</code>
       */
      public Builder setConfirmPasswordBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        confirmPassword_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:model.Register)
    }

    // @@protoc_insertion_point(class_scope:model.Register)
    private static final com.ntuc.income.up.model.RegisterOuterClass.Register DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.ntuc.income.up.model.RegisterOuterClass.Register();
    }

    public static com.ntuc.income.up.model.RegisterOuterClass.Register getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Register>
        PARSER = new com.google.protobuf.AbstractParser<Register>() {
      public Register parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Register(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Register> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Register> getParserForType() {
      return PARSER;
    }

    public com.ntuc.income.up.model.RegisterOuterClass.Register getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface RegistersOrBuilder extends
      // @@protoc_insertion_point(interface_extends:model.Registers)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .model.Register registers = 1;</code>
     */
    java.util.List<com.ntuc.income.up.model.RegisterOuterClass.Register> 
        getRegistersList();
    /**
     * <code>repeated .model.Register registers = 1;</code>
     */
    com.ntuc.income.up.model.RegisterOuterClass.Register getRegisters(int index);
    /**
     * <code>repeated .model.Register registers = 1;</code>
     */
    int getRegistersCount();
    /**
     * <code>repeated .model.Register registers = 1;</code>
     */
    java.util.List<? extends com.ntuc.income.up.model.RegisterOuterClass.RegisterOrBuilder> 
        getRegistersOrBuilderList();
    /**
     * <code>repeated .model.Register registers = 1;</code>
     */
    com.ntuc.income.up.model.RegisterOuterClass.RegisterOrBuilder getRegistersOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code model.Registers}
   */
  public  static final class Registers extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:model.Registers)
      RegistersOrBuilder {
    // Use Registers.newBuilder() to construct.
    private Registers(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Registers() {
      registers_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Registers(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                registers_ = new java.util.ArrayList<com.ntuc.income.up.model.RegisterOuterClass.Register>();
                mutable_bitField0_ |= 0x00000001;
              }
              registers_.add(
                  input.readMessage(com.ntuc.income.up.model.RegisterOuterClass.Register.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          registers_ = java.util.Collections.unmodifiableList(registers_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ntuc.income.up.model.RegisterOuterClass.internal_static_model_Registers_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ntuc.income.up.model.RegisterOuterClass.internal_static_model_Registers_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ntuc.income.up.model.RegisterOuterClass.Registers.class, com.ntuc.income.up.model.RegisterOuterClass.Registers.Builder.class);
    }

    public static final int REGISTERS_FIELD_NUMBER = 1;
    private java.util.List<com.ntuc.income.up.model.RegisterOuterClass.Register> registers_;
    /**
     * <code>repeated .model.Register registers = 1;</code>
     */
    public java.util.List<com.ntuc.income.up.model.RegisterOuterClass.Register> getRegistersList() {
      return registers_;
    }
    /**
     * <code>repeated .model.Register registers = 1;</code>
     */
    public java.util.List<? extends com.ntuc.income.up.model.RegisterOuterClass.RegisterOrBuilder> 
        getRegistersOrBuilderList() {
      return registers_;
    }
    /**
     * <code>repeated .model.Register registers = 1;</code>
     */
    public int getRegistersCount() {
      return registers_.size();
    }
    /**
     * <code>repeated .model.Register registers = 1;</code>
     */
    public com.ntuc.income.up.model.RegisterOuterClass.Register getRegisters(int index) {
      return registers_.get(index);
    }
    /**
     * <code>repeated .model.Register registers = 1;</code>
     */
    public com.ntuc.income.up.model.RegisterOuterClass.RegisterOrBuilder getRegistersOrBuilder(
        int index) {
      return registers_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < registers_.size(); i++) {
        output.writeMessage(1, registers_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < registers_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, registers_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.ntuc.income.up.model.RegisterOuterClass.Registers)) {
        return super.equals(obj);
      }
      com.ntuc.income.up.model.RegisterOuterClass.Registers other = (com.ntuc.income.up.model.RegisterOuterClass.Registers) obj;

      boolean result = true;
      result = result && getRegistersList()
          .equals(other.getRegistersList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getRegistersCount() > 0) {
        hash = (37 * hash) + REGISTERS_FIELD_NUMBER;
        hash = (53 * hash) + getRegistersList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.ntuc.income.up.model.RegisterOuterClass.Registers parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ntuc.income.up.model.RegisterOuterClass.Registers parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ntuc.income.up.model.RegisterOuterClass.Registers parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ntuc.income.up.model.RegisterOuterClass.Registers parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ntuc.income.up.model.RegisterOuterClass.Registers parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ntuc.income.up.model.RegisterOuterClass.Registers parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ntuc.income.up.model.RegisterOuterClass.Registers parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ntuc.income.up.model.RegisterOuterClass.Registers parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ntuc.income.up.model.RegisterOuterClass.Registers parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.ntuc.income.up.model.RegisterOuterClass.Registers parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ntuc.income.up.model.RegisterOuterClass.Registers parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ntuc.income.up.model.RegisterOuterClass.Registers parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.ntuc.income.up.model.RegisterOuterClass.Registers prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code model.Registers}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:model.Registers)
        com.ntuc.income.up.model.RegisterOuterClass.RegistersOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ntuc.income.up.model.RegisterOuterClass.internal_static_model_Registers_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ntuc.income.up.model.RegisterOuterClass.internal_static_model_Registers_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ntuc.income.up.model.RegisterOuterClass.Registers.class, com.ntuc.income.up.model.RegisterOuterClass.Registers.Builder.class);
      }

      // Construct using com.ntuc.income.up.model.RegisterOuterClass.Registers.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getRegistersFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (registersBuilder_ == null) {
          registers_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          registersBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ntuc.income.up.model.RegisterOuterClass.internal_static_model_Registers_descriptor;
      }

      public com.ntuc.income.up.model.RegisterOuterClass.Registers getDefaultInstanceForType() {
        return com.ntuc.income.up.model.RegisterOuterClass.Registers.getDefaultInstance();
      }

      public com.ntuc.income.up.model.RegisterOuterClass.Registers build() {
        com.ntuc.income.up.model.RegisterOuterClass.Registers result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.ntuc.income.up.model.RegisterOuterClass.Registers buildPartial() {
        com.ntuc.income.up.model.RegisterOuterClass.Registers result = new com.ntuc.income.up.model.RegisterOuterClass.Registers(this);
        int from_bitField0_ = bitField0_;
        if (registersBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            registers_ = java.util.Collections.unmodifiableList(registers_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.registers_ = registers_;
        } else {
          result.registers_ = registersBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ntuc.income.up.model.RegisterOuterClass.Registers) {
          return mergeFrom((com.ntuc.income.up.model.RegisterOuterClass.Registers)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ntuc.income.up.model.RegisterOuterClass.Registers other) {
        if (other == com.ntuc.income.up.model.RegisterOuterClass.Registers.getDefaultInstance()) return this;
        if (registersBuilder_ == null) {
          if (!other.registers_.isEmpty()) {
            if (registers_.isEmpty()) {
              registers_ = other.registers_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureRegistersIsMutable();
              registers_.addAll(other.registers_);
            }
            onChanged();
          }
        } else {
          if (!other.registers_.isEmpty()) {
            if (registersBuilder_.isEmpty()) {
              registersBuilder_.dispose();
              registersBuilder_ = null;
              registers_ = other.registers_;
              bitField0_ = (bitField0_ & ~0x00000001);
              registersBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getRegistersFieldBuilder() : null;
            } else {
              registersBuilder_.addAllMessages(other.registers_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ntuc.income.up.model.RegisterOuterClass.Registers parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ntuc.income.up.model.RegisterOuterClass.Registers) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.ntuc.income.up.model.RegisterOuterClass.Register> registers_ =
        java.util.Collections.emptyList();
      private void ensureRegistersIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          registers_ = new java.util.ArrayList<com.ntuc.income.up.model.RegisterOuterClass.Register>(registers_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.ntuc.income.up.model.RegisterOuterClass.Register, com.ntuc.income.up.model.RegisterOuterClass.Register.Builder, com.ntuc.income.up.model.RegisterOuterClass.RegisterOrBuilder> registersBuilder_;

      /**
       * <code>repeated .model.Register registers = 1;</code>
       */
      public java.util.List<com.ntuc.income.up.model.RegisterOuterClass.Register> getRegistersList() {
        if (registersBuilder_ == null) {
          return java.util.Collections.unmodifiableList(registers_);
        } else {
          return registersBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .model.Register registers = 1;</code>
       */
      public int getRegistersCount() {
        if (registersBuilder_ == null) {
          return registers_.size();
        } else {
          return registersBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .model.Register registers = 1;</code>
       */
      public com.ntuc.income.up.model.RegisterOuterClass.Register getRegisters(int index) {
        if (registersBuilder_ == null) {
          return registers_.get(index);
        } else {
          return registersBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .model.Register registers = 1;</code>
       */
      public Builder setRegisters(
          int index, com.ntuc.income.up.model.RegisterOuterClass.Register value) {
        if (registersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRegistersIsMutable();
          registers_.set(index, value);
          onChanged();
        } else {
          registersBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .model.Register registers = 1;</code>
       */
      public Builder setRegisters(
          int index, com.ntuc.income.up.model.RegisterOuterClass.Register.Builder builderForValue) {
        if (registersBuilder_ == null) {
          ensureRegistersIsMutable();
          registers_.set(index, builderForValue.build());
          onChanged();
        } else {
          registersBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .model.Register registers = 1;</code>
       */
      public Builder addRegisters(com.ntuc.income.up.model.RegisterOuterClass.Register value) {
        if (registersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRegistersIsMutable();
          registers_.add(value);
          onChanged();
        } else {
          registersBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .model.Register registers = 1;</code>
       */
      public Builder addRegisters(
          int index, com.ntuc.income.up.model.RegisterOuterClass.Register value) {
        if (registersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRegistersIsMutable();
          registers_.add(index, value);
          onChanged();
        } else {
          registersBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .model.Register registers = 1;</code>
       */
      public Builder addRegisters(
          com.ntuc.income.up.model.RegisterOuterClass.Register.Builder builderForValue) {
        if (registersBuilder_ == null) {
          ensureRegistersIsMutable();
          registers_.add(builderForValue.build());
          onChanged();
        } else {
          registersBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .model.Register registers = 1;</code>
       */
      public Builder addRegisters(
          int index, com.ntuc.income.up.model.RegisterOuterClass.Register.Builder builderForValue) {
        if (registersBuilder_ == null) {
          ensureRegistersIsMutable();
          registers_.add(index, builderForValue.build());
          onChanged();
        } else {
          registersBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .model.Register registers = 1;</code>
       */
      public Builder addAllRegisters(
          java.lang.Iterable<? extends com.ntuc.income.up.model.RegisterOuterClass.Register> values) {
        if (registersBuilder_ == null) {
          ensureRegistersIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, registers_);
          onChanged();
        } else {
          registersBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .model.Register registers = 1;</code>
       */
      public Builder clearRegisters() {
        if (registersBuilder_ == null) {
          registers_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          registersBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .model.Register registers = 1;</code>
       */
      public Builder removeRegisters(int index) {
        if (registersBuilder_ == null) {
          ensureRegistersIsMutable();
          registers_.remove(index);
          onChanged();
        } else {
          registersBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .model.Register registers = 1;</code>
       */
      public com.ntuc.income.up.model.RegisterOuterClass.Register.Builder getRegistersBuilder(
          int index) {
        return getRegistersFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .model.Register registers = 1;</code>
       */
      public com.ntuc.income.up.model.RegisterOuterClass.RegisterOrBuilder getRegistersOrBuilder(
          int index) {
        if (registersBuilder_ == null) {
          return registers_.get(index);  } else {
          return registersBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .model.Register registers = 1;</code>
       */
      public java.util.List<? extends com.ntuc.income.up.model.RegisterOuterClass.RegisterOrBuilder> 
           getRegistersOrBuilderList() {
        if (registersBuilder_ != null) {
          return registersBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(registers_);
        }
      }
      /**
       * <code>repeated .model.Register registers = 1;</code>
       */
      public com.ntuc.income.up.model.RegisterOuterClass.Register.Builder addRegistersBuilder() {
        return getRegistersFieldBuilder().addBuilder(
            com.ntuc.income.up.model.RegisterOuterClass.Register.getDefaultInstance());
      }
      /**
       * <code>repeated .model.Register registers = 1;</code>
       */
      public com.ntuc.income.up.model.RegisterOuterClass.Register.Builder addRegistersBuilder(
          int index) {
        return getRegistersFieldBuilder().addBuilder(
            index, com.ntuc.income.up.model.RegisterOuterClass.Register.getDefaultInstance());
      }
      /**
       * <code>repeated .model.Register registers = 1;</code>
       */
      public java.util.List<com.ntuc.income.up.model.RegisterOuterClass.Register.Builder> 
           getRegistersBuilderList() {
        return getRegistersFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.ntuc.income.up.model.RegisterOuterClass.Register, com.ntuc.income.up.model.RegisterOuterClass.Register.Builder, com.ntuc.income.up.model.RegisterOuterClass.RegisterOrBuilder> 
          getRegistersFieldBuilder() {
        if (registersBuilder_ == null) {
          registersBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.ntuc.income.up.model.RegisterOuterClass.Register, com.ntuc.income.up.model.RegisterOuterClass.Register.Builder, com.ntuc.income.up.model.RegisterOuterClass.RegisterOrBuilder>(
                  registers_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          registers_ = null;
        }
        return registersBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:model.Registers)
    }

    // @@protoc_insertion_point(class_scope:model.Registers)
    private static final com.ntuc.income.up.model.RegisterOuterClass.Registers DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.ntuc.income.up.model.RegisterOuterClass.Registers();
    }

    public static com.ntuc.income.up.model.RegisterOuterClass.Registers getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Registers>
        PARSER = new com.google.protobuf.AbstractParser<Registers>() {
      public Registers parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Registers(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Registers> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Registers> getParserForType() {
      return PARSER;
    }

    public com.ntuc.income.up.model.RegisterOuterClass.Registers getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_model_Register_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_model_Register_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_model_Registers_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_model_Registers_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016register.proto\022\005model\"\254\001\n\010Register\022\030\n\020" +
      "identityTypeList\030\001 \001(\t\022\024\n\014identityType\030\002" +
      " \001(\t\022\023\n\013dateOfBirth\030\003 \001(\t\022\024\n\014emailAddres" +
      "s\030\004 \001(\t\022\032\n\022changeEmailAddress\030\005 \001(\t\022\020\n\010p" +
      "assword\030\006 \001(\t\022\027\n\017confirmPassword\030\007 \001(\t\"/" +
      "\n\tRegisters\022\"\n\tregisters\030\001 \003(\0132\017.model.R" +
      "egisterB\032\n\030com.ntuc.income.up.modelb\006pro" +
      "to3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_model_Register_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_model_Register_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_model_Register_descriptor,
        new java.lang.String[] { "IdentityTypeList", "IdentityType", "DateOfBirth", "EmailAddress", "ChangeEmailAddress", "Password", "ConfirmPassword", });
    internal_static_model_Registers_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_model_Registers_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_model_Registers_descriptor,
        new java.lang.String[] { "Registers", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
